// Song metadata and every playable note live here, separate from the engine.
// This makes it possible to revise the chart without touching app.js.
//
// Lane numbers: 0 = left, 1 = up, 2 = down, 3 = right.
// Author note positions in BEATS, not seconds. At 115 BPM:
//   1 beat = quarter note, 0.5 = eighth note, 0.25 = sixteenth note
//   1 / 3 = eighth-note triplet, 1 / 6 = sixteenth-note triplet
const BPM = 115;
const AUDIO_OFFSET = 0.4644;
const SECONDS_PER_BEAT = 60 / BPM;

// Beat zero is the first charted downbeat. Keep all time conversion here so a
// BPM or audio-offset correction automatically moves the entire chart.
const beatToSeconds = (beat) => AUDIO_OFFSET + beat * SECONDS_PER_BEAT;

// Sections are also authored on the beat grid. A null start means the literal
// beginning of the audio, before beat zero.
const makeSection = (name, startBeat, endBeat) => ({
  name,
  start: startBeat == null ? 0 : beatToSeconds(startBeat),
  end: beatToSeconds(endBeat),
});

window.EYESORE_CHART = {
  title: "Eyesore",
  artist: "Kumo 99",
  bpm: BPM,
  offset: AUDIO_OFFSET,
  difficulty: "Normal 6",
  duration: 145.125,
  // Section boundaries only control the labels; they do not affect judgment.
  sections: [
    makeSection("INTRO", null, 13),
    makeSection("VERSE I", 13, 57.5),
    makeSection("BUILD", 57.5, 90),
    makeSection("CHORUS I", 90, 133.5),
    makeSection("DRIVE", 133.5, 165 + 2 / 3),
    makeSection("BREAK", 165 + 2 / 3, 196),
    makeSection("FINAL", 196, 259.75),
    makeSection("OUTRO", 259.75, 277.5),
  ],
  // Notes with the same beat in different lanes form a two-arrow jump.
  notes: [
    { beat: 0, lane: 0, type: "tap", section: "INTRO" },
    { beat: 2, lane: 3, type: "tap", section: "INTRO" },
    { beat: 4, lane: 3, type: "tap", section: "INTRO" },
    { beat: 6, lane: 0, type: "tap", section: "INTRO" },
    { beat: 7.9167, lane: 0, type: "tap", section: "INTRO" },
    { beat: 9.8333, lane: 3, type: "tap", section: "INTRO" },
    { beat: 11.8333, lane: 3, type: "tap", section: "INTRO" },
    { beat: 14, lane: 0, type: "tap", section: "VERSE I" },
    { beat: 15.1667, lane: 2, type: "tap", section: "VERSE I" },
    { beat: 16.1667, lane: 1, type: "tap", section: "VERSE I" },
    { beat: 18.25, lane: 2, type: "tap", section: "VERSE I" },
    { beat: 19.25, lane: 3, type: "tap", section: "VERSE I" },
    { beat: 20.25, lane: 2, type: "tap", section: "VERSE I" },
    { beat: 22.25, lane: 1, type: "tap", section: "VERSE I" },
    { beat: 23.25, lane: 0, type: "tap", section: "VERSE I" },
    { beat: 24.25, lane: 0, type: "tap", section: "VERSE I" },
    { beat: 26.4167, lane: 1, type: "tap", section: "VERSE I" },
    { beat: 27.5833, lane: 2, type: "tap", section: "VERSE I" },
    { beat: 28.5833, lane: 3, type: "tap", section: "VERSE I" },
    { beat: 30.25, lane: 2, type: "tap", section: "VERSE I" },
    { beat: 31.25, lane: 1, type: "tap", section: "VERSE I" },
    { beat: 32.25, lane: 0, type: "tap", section: "VERSE I" },
    { beat: 34.25, lane: 3, type: "tap", section: "VERSE I" },
    { beat: 36.25, lane: 3, type: "tap", section: "VERSE I" },
    { beat: 38.25, lane: 0, type: "tap", section: "VERSE I" },
    { beat: 39, lane: 1, type: "tap", section: "VERSE I" },
    { beat: 40, lane: 0, type: "tap", section: "VERSE I" },
    { beat: 41.9167, lane: 3, type: "tap", section: "VERSE I" },
    { beat: 42.9167, lane: 1, type: "tap", section: "VERSE I" },
    { beat: 43.9167, lane: 3, type: "tap", section: "VERSE I" },
    { beat: 45.9167, lane: 0, type: "tap", section: "VERSE I" },
    { beat: 47, lane: 2, type: "tap", section: "VERSE I" },
    { beat: 47.9167, lane: 1, type: "tap", section: "VERSE I" },
    { beat: 49.9167, lane: 2, type: "tap", section: "VERSE I" },
    { beat: 50.9167, lane: 3, type: "tap", section: "VERSE I" },
    { beat: 52, lane: 2, type: "tap", section: "VERSE I" },
    { beat: 54, lane: 1, type: "tap", section: "VERSE I" },
    { beat: 55, lane: 0, type: "tap", section: "VERSE I" },
    { beat: 56, lane: 0, type: "tap", section: "VERSE I" },
    { beat: 58, lane: 1, type: "tap", section: "BUILD" },
    { beat: 59, lane: 2, type: "tap", section: "BUILD" },
    { beat: 60, lane: 3, type: "tap", section: "BUILD" },
    { beat: 61, lane: 0, type: "tap", section: "BUILD" },
    { beat: 62, lane: 2, type: "tap", section: "BUILD" },
    { beat: 63, lane: 1, type: "tap", section: "BUILD" },
    { beat: 64.3333, lane: 0, type: "tap", section: "BUILD" },
    { beat: 64.8333, lane: 3, type: "tap", section: "BUILD" },
    { beat: 65.3333, lane: 1, type: "tap", section: "BUILD" },
    { beat: 66.3333, lane: 3, type: "tap", section: "BUILD" },
    { beat: 67, lane: 0, type: "tap", section: "BUILD" },
    { beat: 67.6667, lane: 2, type: "tap", section: "BUILD" },
    { beat: 68.1667, lane: 1, type: "tap", section: "BUILD" },
    { beat: 68.6667, lane: 3, type: "tap", section: "BUILD" },
    { beat: 69.1667, lane: 0, type: "tap", section: "BUILD" },
    { beat: 69.6667, lane: 2, type: "tap", section: "BUILD" },
    { beat: 70.1667, lane: 1, type: "tap", section: "BUILD" },
    { beat: 70.6667, lane: 0, type: "tap", section: "BUILD" },
    { beat: 71.6667, lane: 1, type: "tap", section: "BUILD" },
    { beat: 72.6667, lane: 0, type: "tap", section: "BUILD" },
    { beat: 73.75, lane: 2, type: "tap", section: "BUILD" },
    { beat: 74.6667, lane: 3, type: "tap", section: "BUILD" },
    { beat: 75.75, lane: 1, type: "tap", section: "BUILD" },
    { beat: 76.75, lane: 3, type: "tap", section: "BUILD" },
    { beat: 77.6667, lane: 1, type: "tap", section: "BUILD" },
    { beat: 78.6667, lane: 0, type: "tap", section: "BUILD" },
    { beat: 79.6667, lane: 2, type: "tap", section: "BUILD" },
    { beat: 80.75, lane: 1, type: "tap", section: "BUILD" },
    { beat: 81.75, lane: 0, type: "tap", section: "BUILD" },
    { beat: 82.5833, lane: 2, type: "tap", section: "BUILD" },
    { beat: 83.4167, lane: 3, type: "tap", section: "BUILD" },
    { beat: 84.4167, lane: 2, type: "tap", section: "BUILD" },
    { beat: 85.4167, lane: 3, type: "tap", section: "BUILD" },
    { beat: 86.4167, lane: 1, type: "tap", section: "BUILD" },
    { beat: 87.4167, lane: 0, type: "tap", section: "BUILD" },
    { beat: 88.4167, lane: 0, type: "tap", section: "BUILD" },
    { beat: 89.4167, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 90.4167, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 91.4167, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 92.4167, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 93.4167, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 94.4167, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 95.4167, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 95.9167, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 96.4167, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 97.4167, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 98.4167, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 99.4167, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 100.4167, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 101.4167, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 102.4167, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 103.4167, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 104, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 104.5, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 104.5, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 105.5, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 106.5, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 107.5, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 108.5, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 109.5, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 110.5, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 111.5, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 112, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 112.5, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 113.5, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 114.5, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 115.5, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 116.5, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 117.5, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 118.5, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 119.5, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 120, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 120.5, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 120.5, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 121.5, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 122.5, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 123.5, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 124.5, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 125.5, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 126.5, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 127.5, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 128, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 128.5, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 129, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 129.5, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 130.5, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 131.5, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 132.5, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 133.5833, lane: 2, type: "tap", section: "DRIVE" },
    { beat: 134.25, lane: 1, type: "tap", section: "DRIVE" },
    { beat: 134.8333, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 135.9167, lane: 1, type: "tap", section: "DRIVE" },
    { beat: 136.9167, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 137.9167, lane: 2, type: "tap", section: "DRIVE" },
    { beat: 138.9167, lane: 3, type: "tap", section: "DRIVE" },
    { beat: 139.9167, lane: 1, type: "tap", section: "DRIVE" },
    { beat: 140.9167, lane: 3, type: "tap", section: "DRIVE" },
    { beat: 141.9167, lane: 1, type: "tap", section: "DRIVE" },
    { beat: 142.9167, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 143.9167, lane: 2, type: "tap", section: "DRIVE" },
    { beat: 144.9167, lane: 1, type: "tap", section: "DRIVE" },
    { beat: 145.9167, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 146.9167, lane: 2, type: "tap", section: "DRIVE" },
    { beat: 147.9167, lane: 3, type: "tap", section: "DRIVE" },
    { beat: 148.9167, lane: 2, type: "tap", section: "DRIVE" },
    { beat: 149.4167, lane: 1, type: "tap", section: "DRIVE" },
    { beat: 149.9167, lane: 3, type: "tap", section: "DRIVE" },
    { beat: 150.4167, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 150.9167, lane: 1, type: "tap", section: "DRIVE" },
    { beat: 151.9167, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 152.4167, lane: 3, type: "tap", section: "DRIVE" },
    { beat: 152.9167, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 153.9167, lane: 3, type: "tap", section: "DRIVE" },
    { beat: 154.4167, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 154.9167, lane: 1, type: "tap", section: "DRIVE" },
    { beat: 155.4167, lane: 2, type: "tap", section: "DRIVE" },
    { beat: 155.9167, lane: 2, type: "tap", section: "DRIVE" },
    { beat: 156.4167, lane: 1, type: "tap", section: "DRIVE" },
    { beat: 156.9167, lane: 3, type: "tap", section: "DRIVE" },
    { beat: 157.9167, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 158.4167, lane: 3, type: "tap", section: "DRIVE" },
    { beat: 158.9167, lane: 2, type: "tap", section: "DRIVE" },
    { beat: 159.8333, lane: 1, type: "tap", section: "DRIVE" },
    { beat: 160.6667, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 161.5833, lane: 1, type: "tap", section: "DRIVE" },
    { beat: 162.5833, lane: 3, type: "tap", section: "DRIVE" },
    { beat: 163.5833, lane: 2, type: "tap", section: "DRIVE" },
    { beat: 164.6667, lane: 3, type: "tap", section: "DRIVE" },
    { beat: 165.5833, lane: 2, type: "tap", section: "DRIVE" },
    { beat: 166.6667, lane: 0, type: "tap", section: "BREAK" },
    { beat: 168.6667, lane: 0, type: "tap", section: "BREAK" },
    { beat: 170.6667, lane: 3, type: "tap", section: "BREAK" },
    { beat: 172.6667, lane: 3, type: "tap", section: "BREAK" },
    { beat: 174.6667, lane: 0, type: "tap", section: "BREAK" },
    { beat: 176.6667, lane: 1, type: "tap", section: "BREAK" },
    { beat: 178.6667, lane: 2, type: "tap", section: "BREAK" },
    { beat: 180.6667, lane: 2, type: "tap", section: "BREAK" },
    { beat: 182.5833, lane: 1, type: "tap", section: "BREAK" },
    { beat: 184.3333, lane: 0, type: "tap", section: "BREAK" },
    { beat: 186.3333, lane: 1, type: "tap", section: "BREAK" },
    { beat: 188.3333, lane: 3, type: "tap", section: "BREAK" },
    { beat: 190.3333, lane: 2, type: "tap", section: "BREAK" },
    { beat: 192.3333, lane: 0, type: "tap", section: "BREAK" },
    { beat: 194.4167, lane: 3, type: "tap", section: "BREAK" },
    { beat: 196.4167, lane: 3, type: "tap", section: "BREAK" },
    { beat: 197.4167, lane: 2, type: "tap", section: "FINAL" },
    { beat: 198.4167, lane: 0, type: "tap", section: "FINAL" },
    { beat: 199.4167, lane: 1, type: "tap", section: "FINAL" },
    { beat: 199.9167, lane: 2, type: "tap", section: "FINAL" },
    { beat: 200.4167, lane: 0, type: "tap", section: "FINAL" },
    { beat: 201.4167, lane: 2, type: "tap", section: "FINAL" },
    { beat: 202.4167, lane: 3, type: "tap", section: "FINAL" },
    { beat: 203.4167, lane: 1, type: "tap", section: "FINAL" },
    { beat: 204.4167, lane: 3, type: "tap", section: "FINAL" },
    { beat: 205.4167, lane: 1, type: "tap", section: "FINAL" },
    { beat: 206.4167, lane: 0, type: "tap", section: "FINAL" },
    { beat: 207.4167, lane: 2, type: "tap", section: "FINAL" },
    { beat: 207.9167, lane: 1, type: "tap", section: "FINAL" },
    { beat: 208.4167, lane: 1, type: "tap", section: "FINAL" },
    { beat: 209.4167, lane: 0, type: "tap", section: "FINAL" },
    { beat: 210.4167, lane: 2, type: "tap", section: "FINAL" },
    { beat: 211.4167, lane: 3, type: "tap", section: "FINAL" },
    { beat: 212.4167, lane: 2, type: "tap", section: "FINAL" },
    { beat: 213.4167, lane: 3, type: "tap", section: "FINAL" },
    { beat: 214.4167, lane: 1, type: "tap", section: "FINAL" },
    { beat: 215.4167, lane: 0, type: "tap", section: "FINAL" },
    { beat: 215.9167, lane: 3, type: "tap", section: "FINAL" },
    { beat: 216.4167, lane: 0, type: "tap", section: "FINAL" },
    { beat: 216.4167, lane: 3, type: "tap", section: "FINAL" },
    { beat: 217.4167, lane: 3, type: "tap", section: "FINAL" },
    { beat: 217.9167, lane: 0, type: "tap", section: "FINAL" },
    { beat: 218.4167, lane: 1, type: "tap", section: "FINAL" },
    { beat: 219.5, lane: 2, type: "tap", section: "FINAL" },
    { beat: 220.5, lane: 3, type: "tap", section: "FINAL" },
    { beat: 221.5, lane: 0, type: "tap", section: "FINAL" },
    { beat: 222.5, lane: 2, type: "tap", section: "FINAL" },
    { beat: 223.5, lane: 1, type: "tap", section: "FINAL" },
    { beat: 224, lane: 2, type: "tap", section: "FINAL" },
    { beat: 224.5, lane: 0, type: "tap", section: "FINAL" },
    { beat: 225.5, lane: 1, type: "tap", section: "FINAL" },
    { beat: 226.5, lane: 3, type: "tap", section: "FINAL" },
    { beat: 227.5, lane: 2, type: "tap", section: "FINAL" },
    { beat: 228.5, lane: 3, type: "tap", section: "FINAL" },
    { beat: 229.5, lane: 2, type: "tap", section: "FINAL" },
    { beat: 230.5, lane: 0, type: "tap", section: "FINAL" },
    { beat: 231.5, lane: 1, type: "tap", section: "FINAL" },
    { beat: 232, lane: 2, type: "tap", section: "FINAL" },
    { beat: 232.5, lane: 0, type: "tap", section: "FINAL" },
    { beat: 232.5, lane: 3, type: "tap", section: "FINAL" },
    { beat: 233.5, lane: 2, type: "tap", section: "FINAL" },
    { beat: 234.5, lane: 3, type: "tap", section: "FINAL" },
    { beat: 235.5, lane: 1, type: "tap", section: "FINAL" },
    { beat: 236.5, lane: 3, type: "tap", section: "FINAL" },
    { beat: 237.5, lane: 1, type: "tap", section: "FINAL" },
    { beat: 238.5, lane: 0, type: "tap", section: "FINAL" },
    { beat: 239.5, lane: 2, type: "tap", section: "FINAL" },
    { beat: 240, lane: 1, type: "tap", section: "FINAL" },
    { beat: 240.5, lane: 1, type: "tap", section: "FINAL" },
    { beat: 241.5, lane: 0, type: "tap", section: "FINAL" },
    { beat: 242.1667, lane: 3, type: "tap", section: "FINAL" },
    { beat: 242.8333, lane: 2, type: "tap", section: "FINAL" },
    { beat: 243.8333, lane: 3, type: "tap", section: "FINAL" },
    { beat: 244.8333, lane: 2, type: "tap", section: "FINAL" },
    { beat: 245.9167, lane: 3, type: "tap", section: "FINAL" },
    { beat: 246.5833, lane: 0, type: "tap", section: "FINAL" },
    { beat: 247.1667, lane: 1, type: "tap", section: "FINAL" },
    { beat: 248.25, lane: 0, type: "tap", section: "FINAL" },
    { beat: 248.75, lane: 3, type: "tap", section: "FINAL" },
    { beat: 249.25, lane: 0, type: "tap", section: "FINAL" },
    { beat: 249.25, lane: 3, type: "tap", section: "FINAL" },
    { beat: 250.25, lane: 3, type: "tap", section: "FINAL" },
    { beat: 251.25, lane: 1, type: "tap", section: "FINAL" },
    { beat: 252.25, lane: 2, type: "tap", section: "FINAL" },
    { beat: 253.25, lane: 3, type: "tap", section: "FINAL" },
    { beat: 254.25, lane: 0, type: "tap", section: "FINAL" },
    { beat: 255.25, lane: 2, type: "tap", section: "FINAL" },
    { beat: 256.25, lane: 1, type: "tap", section: "FINAL" },
    { beat: 256.75, lane: 2, type: "tap", section: "FINAL" },
    { beat: 257.25, lane: 0, type: "tap", section: "FINAL" },
    { beat: 258.25, lane: 1, type: "tap", section: "FINAL" },
    { beat: 259.25, lane: 3, type: "tap", section: "FINAL" },
    { beat: 261.25, lane: 3, type: "tap", section: "OUTRO" },
    { beat: 263.25, lane: 0, type: "tap", section: "OUTRO" },
    { beat: 265.25, lane: 0, type: "tap", section: "OUTRO" },
  ].map((note) => ({ ...note, time: beatToSeconds(note.beat) })),
};
