// Song metadata and every playable note live here, separate from the engine.
// This makes it possible to revise the chart without touching app.js.
//
// Lane numbers: 0 = left, 1 = up, 2 = down, 3 = right.
// Author note positions in BEATS, not seconds. At 115 BPM:
//   1 beat = quarter note, 0.5 = eighth note, 0.25 = sixteenth note
//   1 / 3 = eighth-note triplet, 1 / 6 = sixteenth-note triplet
const BPM = 115;
const AUDIO_OFFSET = 0.4644;
const SECONDS_PER_BEAT = 60 / BPM;

// Beat zero is the first charted downbeat. Keep all time conversion here so a
// BPM or audio-offset correction automatically moves the entire chart.
const beatToSeconds = (beat) => AUDIO_OFFSET + beat * SECONDS_PER_BEAT;

// Sections are also authored on the beat grid. A null start means the literal
// beginning of the audio, before beat zero.
const makeSection = (name, startBeat, endBeat) => ({
  name,
  start: startBeat == null ? 0 : beatToSeconds(startBeat),
  end: beatToSeconds(endBeat),
});

window.EYESORE_CHART = {
  title: "Eyesore",
  artist: "Kumo 99",
  bpm: BPM,
  offset: AUDIO_OFFSET,
  difficulty: "Normal 6",
  duration: 145.125,
  // Section boundaries only control the labels; they do not affect judgment.
  sections: [
    makeSection("INTRO", null, 13),
    makeSection("VERSE I", 13, 57.5),
    makeSection("BUILD", 57.5, 90),
    makeSection("CHORUS I", 90, 133.5),
    makeSection("DRIVE", 133.5, 165 + 2 / 3),
    makeSection("BREAK", 165 + 2 / 3, 196),
    makeSection("FINAL", 196, 259.75),
    makeSection("OUTRO", 259.75, 277.5),
  ],
  // Notes with the same beat in different lanes form a two-arrow jump.
  notes: [
    { beat: 10.25, lane: 0, type: "tap", section: "INTRO" },
    { beat: 15.25, lane: 3, type: "tap", section: "VERSE I" },
    { beat: 20.5, lane: 0, type: "tap", section: "VERSE I" },
    { beat: 20.5, lane: 3, type: "tap", section: "VERSE I" },
    { beat: 25.75, lane: 0, type: "tap", section: "VERSE I" },
    { beat: 25.75, lane: 3, type: "tap", section: "VERSE I" },
    { beat: 26.5, lane: 1, type: "tap", section: "VERSE I" },
    { beat: 31.25, lane: 0, type: "tap", section: "VERSE I" },
    { beat: 31.25, lane: 3, type: "tap", section: "VERSE I" },
    { beat: 32, lane: 1, type: "tap", section: "VERSE I" },
    { beat: 32.5, lane: 2, type: "tap", section: "VERSE I" },
    { beat: 33.25, lane: 1, type: "tap", section: "VERSE I" },
    { beat: 33.75, lane: 2, type: "tap", section: "VERSE I" },
    { beat: 34.5, lane: 0, type: "tap", section: "VERSE I" },
    { beat: 35.25, lane: 3, type: "tap", section: "VERSE I" },
    { beat: 36, lane: 1, type: "tap", section: "VERSE I" },
    { beat: 36.5, lane: 2, type: "tap", section: "VERSE I" },
    { beat: 37.25, lane: 0, type: "tap", section: "VERSE I" },
    { beat: 38, lane: 3, type: "tap", section: "VERSE I" },
    { beat: 38.5, lane: 1, type: "tap", section: "VERSE I" },
    { beat: 39.25, lane: 2, type: "tap", section: "VERSE I" },
    { beat: 40, lane: 0, type: "tap", section: "VERSE I" },
    { beat: 40.5, lane: 3, type: "tap", section: "VERSE I" },
    { beat: 41.25, lane: 1, type: "tap", section: "VERSE I" },
    { beat: 42, lane: 0, type: "tap", section: "VERSE I" },
    { beat: 42, lane: 3, type: "tap", section: "VERSE I" },
    { beat: 45.25, lane: 1, type: "tap", section: "VERSE I" },
    { beat: 45.5, lane: 1, type: "tap", section: "VERSE I" },
    { beat: 46.5, lane: 1, type: "tap", section: "VERSE I" },
    { beat: 47.25, lane: 0, type: "tap", section: "VERSE I" },
    { beat: 47.25, lane: 3, type: "tap", section: "VERSE I" },
    { beat: 49.25, lane: 2, type: "tap", section: "VERSE I" },
    { beat: 50, lane: 1, type: "tap", section: "VERSE I" },
    { beat: 50.75, lane: 2, type: "tap", section: "VERSE I" },
    { beat: 51.25, lane: 0, type: "tap", section: "VERSE I" },
    { beat: 52, lane: 3, type: "tap", section: "VERSE I" },
    { beat: 52.75, lane: 0, type: "tap", section: "VERSE I" },
    { beat: 52.75, lane: 3, type: "tap", section: "VERSE I" },
    { beat: 56, lane: 0, type: "tap", section: "VERSE I" },
    { beat: 56.75, lane: 1, type: "tap", section: "VERSE I" },
    { beat: 57.25, lane: 2, type: "tap", section: "VERSE I" },
    { beat: 58, lane: 3, type: "tap", section: "BUILD" },
    { beat: 58.75, lane: 0, type: "tap", section: "BUILD" },
    { beat: 59.25, lane: 1, type: "tap", section: "BUILD" },
    { beat: 60, lane: 2, type: "tap", section: "BUILD" },
    { beat: 60.5, lane: 3, type: "tap", section: "BUILD" },
    { beat: 61.25, lane: 0, type: "tap", section: "BUILD" },
    { beat: 62, lane: 1, type: "tap", section: "BUILD" },
    { beat: 62.5, lane: 2, type: "tap", section: "BUILD" },
    { beat: 63.25, lane: 0, type: "tap", section: "BUILD" },
    { beat: 63.25, lane: 3, type: "tap", section: "BUILD" },
    { beat: 67.75, lane: 0, type: "tap", section: "BUILD" },
    { beat: 68, lane: 3, type: "tap", section: "BUILD" },
    { beat: 68.75, lane: 1, type: "tap", section: "BUILD" },
    { beat: 68.75, lane: 2, type: "tap", section: "BUILD" },
    { beat: 72, lane: 0, type: "tap", section: "BUILD" },
    { beat: 72.5, lane: 3, type: "tap", section: "BUILD" },
    { beat: 73, lane: 0, type: "tap", section: "BUILD" },
    { beat: 73.5, lane: 3, type: "tap", section: "BUILD" },
    { beat: 73.75, lane: 0, type: "tap", section: "BUILD" },
    { beat: 74, lane: 1, type: "tap", section: "BUILD" },
    { beat: 74.75, lane: 2, type: "tap", section: "BUILD" },
    { beat: 75.5, lane: 0, type: "tap", section: "BUILD" },
    { beat: 76, lane: 3, type: "tap", section: "BUILD" },
    { beat: 76.75, lane: 0, type: "tap", section: "BUILD" },
    { beat: 77.5, lane: 3, type: "tap", section: "BUILD" },
    { beat: 78, lane: 1, type: "tap", section: "BUILD" },
    { beat: 78.25, lane: 0, type: "tap", section: "BUILD" },
    { beat: 78.75, lane: 2, type: "tap", section: "BUILD" },
    { beat: 79, lane: 3, type: "tap", section: "BUILD" },
    { beat: 79.5, lane: 1, type: "tap", section: "BUILD" },
    { beat: 80.25, lane: 1, type: "tap", section: "BUILD" },
    { beat: 80.75, lane: 2, type: "tap", section: "BUILD" },
    { beat: 81.5, lane: 1, type: "tap", section: "BUILD" },
    { beat: 82, lane: 2, type: "tap", section: "BUILD" },
    { beat: 82.75, lane: 0, type: "tap", section: "BUILD" },
    { beat: 83.5, lane: 3, type: "tap", section: "BUILD" },
    { beat: 83.75, lane: 0, type: "tap", section: "BUILD" },
    { beat: 83.75, lane: 3, type: "tap", section: "BUILD" },
    { beat: 84.5, lane: 1, type: "tap", section: "BUILD" },
    { beat: 85, lane: 2, type: "tap", section: "BUILD" },
    { beat: 85.5, lane: 0, type: "tap", section: "BUILD" },
    { beat: 85.5, lane: 3, type: "tap", section: "BUILD" },
    { beat: 86.5, lane: 1, type: "tap", section: "BUILD" },
    { beat: 86.75, lane: 2, type: "tap", section: "BUILD" },
    { beat: 87.5, lane: 0, type: "tap", section: "BUILD" },
    { beat: 88, lane: 3, type: "tap", section: "BUILD" },
    { beat: 88.5, lane: 0, type: "tap", section: "BUILD" },
    { beat: 88.5, lane: 3, type: "tap", section: "BUILD" },
    { beat: 89.25, lane: 1, type: "tap", section: "BUILD" },
    { beat: 89.5, lane: 2, type: "tap", section: "BUILD" },
    { beat: 90, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 90.75, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 91.25, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 91.75, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 92, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 92.5, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 92.75, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 93.25, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 93.5, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 93.75, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 94, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 94.5, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 94.75, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 95, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 95.5, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 95.75, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 96.25, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 96.5, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 96.75, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 97.25, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 97.5, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 97.75, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 98, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 98.5, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 98.75, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 99, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 99.5, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 99.75, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 100.25, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 100.5, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 100.75, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 101.25, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 101.5, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 101.75, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 102.25, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 102.5, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 102.75, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 103, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 103.5, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 103.75, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 104.25, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 104.5, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 104.75, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 105, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 105.5, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 105.75, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 106.25, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 106.25, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 106.75, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 106.75, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 107.5, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 107.5, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 108, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 108.25, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 108.75, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 108.75, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 109.5, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 110.25, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 110.25, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 110.75, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 111, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 111.5, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 111.5, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 112.25, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 112.25, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 112.75, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 112.75, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 113.5, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 113.5, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 114.25, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 114.25, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 114.75, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 114.75, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 115.5, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 115.5, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 115.5, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 116.25, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 116.25, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 116.75, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 117.5, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 118, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 118.25, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 119.25, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 119.75, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 120.25, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 120.75, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 121.5, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 121.75, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 122.25, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 122.75, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 123.5, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 124.25, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 124.75, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 125.5, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 126.25, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 126.5, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 127, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 127.5, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 128.25, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 129, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 129.25, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 129.5, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 129.75, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 130.5, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 130.75, lane: 1, type: "tap", section: "CHORUS I" },
    { beat: 131.25, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 131.5, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 132, lane: 2, type: "tap", section: "CHORUS I" },
    { beat: 132.25, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 132.5, lane: 3, type: "tap", section: "CHORUS I" },
    { beat: 133, lane: 0, type: "tap", section: "CHORUS I" },
    { beat: 133.5, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 134.25, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 134.5, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 134.75, lane: 1, type: "tap", section: "DRIVE" },
    { beat: 135.25, lane: 2, type: "tap", section: "DRIVE" },
    { beat: 135.75, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 136.5, lane: 3, type: "tap", section: "DRIVE" },
    { beat: 136.75, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 137.25, lane: 3, type: "tap", section: "DRIVE" },
    { beat: 137.5, lane: 1, type: "tap", section: "DRIVE" },
    { beat: 138, lane: 2, type: "tap", section: "DRIVE" },
    { beat: 138.25, lane: 2, type: "tap", section: "DRIVE" },
    { beat: 139, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 139.5, lane: 3, type: "tap", section: "DRIVE" },
    { beat: 140, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 140.5, lane: 3, type: "tap", section: "DRIVE" },
    { beat: 141.25, lane: 3, type: "tap", section: "DRIVE" },
    { beat: 141.5, lane: 3, type: "tap", section: "DRIVE" },
    { beat: 142.25, lane: 1, type: "tap", section: "DRIVE" },
    { beat: 143, lane: 2, type: "tap", section: "DRIVE" },
    { beat: 143.5, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 143.5, lane: 3, type: "tap", section: "DRIVE" },
    { beat: 144.25, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 144.25, lane: 3, type: "tap", section: "DRIVE" },
    { beat: 145, lane: 1, type: "tap", section: "DRIVE" },
    { beat: 145.5, lane: 1, type: "tap", section: "DRIVE" },
    { beat: 146.25, lane: 2, type: "tap", section: "DRIVE" },
    { beat: 146.75, lane: 1, type: "tap", section: "DRIVE" },
    { beat: 147.5, lane: 2, type: "tap", section: "DRIVE" },
    { beat: 147.75, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 148.25, lane: 3, type: "tap", section: "DRIVE" },
    { beat: 148.5, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 149.5, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 150.75, lane: 3, type: "tap", section: "DRIVE" },
    { beat: 151, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 151.75, lane: 3, type: "tap", section: "DRIVE" },
    { beat: 152.25, lane: 1, type: "tap", section: "DRIVE" },
    { beat: 153, lane: 2, type: "tap", section: "DRIVE" },
    { beat: 153.25, lane: 2, type: "tap", section: "DRIVE" },
    { beat: 153.75, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 154, lane: 3, type: "tap", section: "DRIVE" },
    { beat: 154.25, lane: 1, type: "tap", section: "DRIVE" },
    { beat: 155, lane: 1, type: "tap", section: "DRIVE" },
    { beat: 155.75, lane: 2, type: "tap", section: "DRIVE" },
    { beat: 156, lane: 2, type: "tap", section: "DRIVE" },
    { beat: 156.25, lane: 2, type: "tap", section: "DRIVE" },
    { beat: 156.5, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 157.25, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 158, lane: 3, type: "tap", section: "DRIVE" },
    { beat: 158.25, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 158.5, lane: 3, type: "tap", section: "DRIVE" },
    { beat: 159, lane: 1, type: "tap", section: "DRIVE" },
    { beat: 159.25, lane: 1, type: "tap", section: "DRIVE" },
    { beat: 159.75, lane: 2, type: "tap", section: "DRIVE" },
    { beat: 163.25, lane: 2, type: "tap", section: "DRIVE" },
    { beat: 163.5, lane: 2, type: "tap", section: "DRIVE" },
    { beat: 164.25, lane: 2, type: "tap", section: "DRIVE" },
    { beat: 165.5, lane: 0, type: "tap", section: "DRIVE" },
    { beat: 166, lane: 0, type: "tap", section: "BREAK" },
    { beat: 166.75, lane: 0, type: "tap", section: "BREAK" },
    { beat: 167.75, lane: 0, type: "tap", section: "BREAK" },
    { beat: 168.25, lane: 3, type: "tap", section: "BREAK" },
    { beat: 168.75, lane: 3, type: "tap", section: "BREAK" },
    { beat: 169.5, lane: 1, type: "tap", section: "BREAK" },
    { beat: 171.25, lane: 0, type: "tap", section: "BREAK" },
    { beat: 171.25, lane: 2, type: "tap", section: "BREAK" },
    { beat: 172.25, lane: 0, type: "tap", section: "BREAK" },
    { beat: 172.25, lane: 2, type: "tap", section: "BREAK" },
    { beat: 173, lane: 2, type: "tap", section: "BREAK" },
    { beat: 173, lane: 3, type: "tap", section: "BREAK" },
    { beat: 174, lane: 2, type: "tap", section: "BREAK" },
    { beat: 174, lane: 3, type: "tap", section: "BREAK" },
    { beat: 175, lane: 0, type: "tap", section: "BREAK" },
    { beat: 175, lane: 2, type: "tap", section: "BREAK" },
    { beat: 175.75, lane: 2, type: "tap", section: "BREAK" },
    { beat: 175.75, lane: 3, type: "tap", section: "BREAK" },
    { beat: 176.25, lane: 0, type: "tap", section: "BREAK" },
    { beat: 176.25, lane: 2, type: "tap", section: "BREAK" },
    { beat: 177, lane: 2, type: "tap", section: "BREAK" },
    { beat: 177, lane: 3, type: "tap", section: "BREAK" },
    { beat: 177.75, lane: 0, type: "tap", section: "BREAK" },
    { beat: 177.75, lane: 2, type: "tap", section: "BREAK" },
    { beat: 177.75, lane: 3, type: "tap", section: "BREAK" },
    { beat: 178.5, lane: 2, type: "tap", section: "BREAK" },
    { beat: 178.5, lane: 3, type: "tap", section: "BREAK" },
    { beat: 179, lane: 0, type: "tap", section: "BREAK" },
    { beat: 179, lane: 1, type: "tap", section: "BREAK" },
    { beat: 179.75, lane: 2, type: "tap", section: "BREAK" },
    { beat: 180.25, lane: 0, type: "tap", section: "BREAK" },
    { beat: 180.25, lane: 3, type: "tap", section: "BREAK" },
    { beat: 181, lane: 1, type: "tap", section: "BREAK" },
    { beat: 181.75, lane: 0, type: "tap", section: "BREAK" },
    { beat: 185.75, lane: 1, type: "tap", section: "BREAK" },
    { beat: 186.5, lane: 1, type: "tap", section: "BREAK" },
    { beat: 191.75, lane: 1, type: "tap", section: "BREAK" },
    { beat: 197, lane: 1, type: "tap", section: "FINAL" },
    { beat: 198.25, lane: 1, type: "tap", section: "FINAL" },
    { beat: 199.75, lane: 1, type: "tap", section: "FINAL" },
    { beat: 200.25, lane: 0, type: "tap", section: "FINAL" },
    { beat: 201, lane: 3, type: "tap", section: "FINAL" },
    { beat: 201.25, lane: 0, type: "tap", section: "FINAL" },
    { beat: 201.75, lane: 3, type: "tap", section: "FINAL" },
    { beat: 202, lane: 0, type: "tap", section: "FINAL" },
    { beat: 202.5, lane: 0, type: "tap", section: "FINAL" },
    { beat: 202.5, lane: 3, type: "tap", section: "FINAL" },
    { beat: 203.25, lane: 3, type: "tap", section: "FINAL" },
    { beat: 203.75, lane: 0, type: "tap", section: "FINAL" },
    { beat: 204.5, lane: 3, type: "tap", section: "FINAL" },
    { beat: 205, lane: 1, type: "tap", section: "FINAL" },
    { beat: 205.75, lane: 1, type: "tap", section: "FINAL" },
    { beat: 206.25, lane: 2, type: "tap", section: "FINAL" },
    { beat: 207, lane: 0, type: "tap", section: "FINAL" },
    { beat: 207.25, lane: 1, type: "tap", section: "FINAL" },
    { beat: 207.75, lane: 2, type: "tap", section: "FINAL" },
    { beat: 208.5, lane: 2, type: "tap", section: "FINAL" },
    { beat: 209, lane: 0, type: "tap", section: "FINAL" },
    { beat: 209.75, lane: 3, type: "tap", section: "FINAL" },
    { beat: 210.5, lane: 1, type: "tap", section: "FINAL" },
    { beat: 211, lane: 1, type: "tap", section: "FINAL" },
    { beat: 211.75, lane: 2, type: "tap", section: "FINAL" },
    { beat: 212.25, lane: 0, type: "tap", section: "FINAL" },
    { beat: 212.75, lane: 3, type: "tap", section: "FINAL" },
    { beat: 213, lane: 0, type: "tap", section: "FINAL" },
    { beat: 213.75, lane: 1, type: "tap", section: "FINAL" },
    { beat: 214.5, lane: 1, type: "tap", section: "FINAL" },
    { beat: 215.25, lane: 1, type: "tap", section: "FINAL" },
    { beat: 215.75, lane: 2, type: "tap", section: "FINAL" },
    { beat: 216.5, lane: 2, type: "tap", section: "FINAL" },
    { beat: 217, lane: 0, type: "tap", section: "FINAL" },
    { beat: 217.75, lane: 3, type: "tap", section: "FINAL" },
    { beat: 218, lane: 0, type: "tap", section: "FINAL" },
    { beat: 218.5, lane: 1, type: "tap", section: "FINAL" },
    { beat: 219, lane: 2, type: "tap", section: "FINAL" },
    { beat: 219.75, lane: 2, type: "tap", section: "FINAL" },
    { beat: 220.5, lane: 2, type: "tap", section: "FINAL" },
    { beat: 221, lane: 2, type: "tap", section: "FINAL" },
    { beat: 221.5, lane: 2, type: "tap", section: "FINAL" },
    { beat: 221.75, lane: 2, type: "tap", section: "FINAL" },
    { beat: 222.25, lane: 2, type: "tap", section: "FINAL" },
    { beat: 222.5, lane: 0, type: "tap", section: "FINAL" },
    { beat: 222.5, lane: 3, type: "tap", section: "FINAL" },
    { beat: 222.75, lane: 0, type: "tap", section: "FINAL" },
    { beat: 222.75, lane: 3, type: "tap", section: "FINAL" },
    { beat: 223.25, lane: 0, type: "tap", section: "FINAL" },
    { beat: 223.25, lane: 3, type: "tap", section: "FINAL" },
    { beat: 223.5, lane: 0, type: "tap", section: "FINAL" },
    { beat: 223.5, lane: 3, type: "tap", section: "FINAL" },
    { beat: 223.75, lane: 0, type: "tap", section: "FINAL" },
    { beat: 223.75, lane: 3, type: "tap", section: "FINAL" },
    { beat: 224.5, lane: 0, type: "tap", section: "FINAL" },
    { beat: 224.75, lane: 3, type: "tap", section: "FINAL" },
    { beat: 225.25, lane: 0, type: "tap", section: "FINAL" },
    { beat: 225.5, lane: 3, type: "tap", section: "FINAL" },
    { beat: 226, lane: 0, type: "tap", section: "FINAL" },
    { beat: 226.25, lane: 1, type: "tap", section: "FINAL" },
    { beat: 226.5, lane: 1, type: "tap", section: "FINAL" },
    { beat: 226.5, lane: 2, type: "tap", section: "FINAL" },
    { beat: 227, lane: 2, type: "tap", section: "FINAL" },
    { beat: 227.25, lane: 2, type: "tap", section: "FINAL" },
    { beat: 228, lane: 0, type: "tap", section: "FINAL" },
    { beat: 228.5, lane: 1, type: "tap", section: "FINAL" },
    { beat: 229.25, lane: 0, type: "tap", section: "FINAL" },
    { beat: 229.5, lane: 1, type: "tap", section: "FINAL" },
    { beat: 229.75, lane: 0, type: "tap", section: "FINAL" },
    { beat: 230.5, lane: 3, type: "tap", section: "FINAL" },
    { beat: 230.75, lane: 0, type: "tap", section: "FINAL" },
    { beat: 231.25, lane: 0, type: "tap", section: "FINAL" },
    { beat: 231.25, lane: 1, type: "tap", section: "FINAL" },
    { beat: 231.75, lane: 2, type: "tap", section: "FINAL" },
    { beat: 232.25, lane: 2, type: "tap", section: "FINAL" },
    { beat: 232.5, lane: 2, type: "tap", section: "FINAL" },
    { beat: 233, lane: 0, type: "tap", section: "FINAL" },
    { beat: 233.75, lane: 3, type: "tap", section: "FINAL" },
    { beat: 234.5, lane: 1, type: "tap", section: "FINAL" },
    { beat: 235.25, lane: 1, type: "tap", section: "FINAL" },
    { beat: 235.75, lane: 0, type: "tap", section: "FINAL" },
    { beat: 236, lane: 0, type: "tap", section: "FINAL" },
    { beat: 236.5, lane: 0, type: "tap", section: "FINAL" },
    { beat: 237, lane: 3, type: "tap", section: "FINAL" },
    { beat: 237.5, lane: 3, type: "tap", section: "FINAL" },
    { beat: 237.75, lane: 3, type: "tap", section: "FINAL" },
    { beat: 238.5, lane: 1, type: "tap", section: "FINAL" },
    { beat: 238.75, lane: 1, type: "tap", section: "FINAL" },
    { beat: 239, lane: 1, type: "tap", section: "FINAL" },
    { beat: 239.75, lane: 2, type: "tap", section: "FINAL" },
    { beat: 240.5, lane: 0, type: "tap", section: "FINAL" },
    { beat: 241.25, lane: 1, type: "tap", section: "FINAL" },
    { beat: 241.5, lane: 2, type: "tap", section: "FINAL" },
    { beat: 241.75, lane: 0, type: "tap", section: "FINAL" },
    { beat: 242.25, lane: 3, type: "tap", section: "FINAL" },
    { beat: 242.75, lane: 1, type: "tap", section: "FINAL" },
    { beat: 243.25, lane: 2, type: "tap", section: "FINAL" },
    { beat: 243.75, lane: 0, type: "tap", section: "FINAL" },
    { beat: 245.25, lane: 0, type: "tap", section: "FINAL" },
    { beat: 246, lane: 0, type: "tap", section: "FINAL" },
    { beat: 246.5, lane: 3, type: "tap", section: "FINAL" },
    { beat: 247.25, lane: 3, type: "tap", section: "FINAL" },
    { beat: 247.75, lane: 1, type: "tap", section: "FINAL" },
    { beat: 248.5, lane: 1, type: "tap", section: "FINAL" },
    { beat: 249.25, lane: 2, type: "tap", section: "FINAL" },
    { beat: 250, lane: 2, type: "tap", section: "FINAL" },
    { beat: 250.25, lane: 0, type: "tap", section: "FINAL" },
    { beat: 250.75, lane: 3, type: "tap", section: "FINAL" },
    { beat: 251.25, lane: 0, type: "tap", section: "FINAL" },
    { beat: 252.25, lane: 0, type: "tap", section: "FINAL" },
    { beat: 252.5, lane: 0, type: "tap", section: "FINAL" },
    { beat: 253.25, lane: 1, type: "tap", section: "FINAL" },
    { beat: 254, lane: 1, type: "tap", section: "FINAL" },
    { beat: 254.5, lane: 3, type: "tap", section: "FINAL" },
    { beat: 255.25, lane: 3, type: "tap", section: "FINAL" },
    { beat: 256, lane: 0, type: "tap", section: "FINAL" },
    { beat: 256.5, lane: 0, type: "tap", section: "FINAL" },
    { beat: 257.25, lane: 3, type: "tap", section: "FINAL" },
    { beat: 257.75, lane: 3, type: "tap", section: "FINAL" },
    { beat: 258.5, lane: 1, type: "tap", section: "FINAL" },
    { beat: 259.25, lane: 1, type: "tap", section: "FINAL" },
    { beat: 260, lane: 2, type: "tap", section: "OUTRO" },
    { beat: 260.5, lane: 2, type: "tap", section: "OUTRO" },
    { beat: 261.25, lane: 0, type: "tap", section: "OUTRO" },
    { beat: 262, lane: 0, type: "tap", section: "OUTRO" },
    { beat: 262.5, lane: 3, type: "tap", section: "OUTRO" },
    { beat: 263.25, lane: 3, type: "tap", section: "OUTRO" },
    { beat: 263.75, lane: 1, type: "tap", section: "OUTRO" },
    { beat: 264.5, lane: 1, type: "tap", section: "OUTRO" },
    { beat: 265.25, lane: 2, type: "tap", section: "OUTRO" },
    { beat: 266, lane: 2, type: "tap", section: "OUTRO" },
    { beat: 266.5, lane: 3, type: "tap", section: "OUTRO" },
    { beat: 266.75, lane: 0, type: "tap", section: "OUTRO" },
  ].map((note) => ({ ...note, time: beatToSeconds(note.beat) })),
};