CREATE TABLE IF NOT EXISTS scores (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  initials TEXT NOT NULL CHECK(length(initials) BETWEEN 1 AND 3),
  score INTEGER NOT NULL CHECK(score BETWEEN 0 AND 2000000),
  accuracy REAL NOT NULL CHECK(accuracy BETWEEN 0 AND 100),
  combo INTEGER NOT NULL CHECK(combo BETWEEN 0 AND 1000),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS scores_ranking
ON scores(score DESC, accuracy DESC, created_at ASC);
